/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 console.glb 
Author: adilvr (https://sketchfab.com/adilvr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/playstation-5-ps5-box-packaging-99ad5ab33b714a4a92efc4e37bac4c75
Title: PlayStation 5 PS5 Box Packaging
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ConsoleModel(props) {
  const { nodes, materials } = useGLTF('/consoleModel.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.112}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[0, 21.93, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/consoleModel.glb')
